#!/bin/bash
#SBATCH --job-name=testbraken		# Job name (testBowtie2)
#SBATCH --partition=highmem_p		# Partition name (batch, highmem_p, or gpu_p)
#SBATCH --ntasks=1	# Run job in single task, by default using 1 CPU core on a single node
#SBATCH --cpus-per-task=12	 # CPU core count per task, by default 1 CPU core per task
#SBATCH --mem=80		# Memory per node (4GB); by default using M as unit
#SBATCH --time=20:00:00              	# Time limit hrs:min:sec or days-hours:minutes:seconds
#SBATCH --output=%x_%j.out		# Standard output log, e.g., testBowtie2_12345.out
#SBATCH --error=%x_%j.err		# Standard error log, e.g., testBowtie2_12345.err
#SBATCH --mail-user=peavy@uga.edu    # Where to send mail
#SBATCH --mail-type=ALL          	# Mail events (BEGIN, END, FAIL, ALL)
cd $SLURM_SUBMIT_DIR			# Change directory to job submission directory (Optional!)

source ~/miniconda3/bin/activate

conda init

conda activate kraken

# download taxonomy files first
kraken2-build --download-taxonomy --db microbiome

# download input files for kraken2 custom database
kraken2-build --download-library archaea --db microbiome
kraken2-build --download-library viral --db microbiome
kraken2-build --download-library bacteria --db microbiome

# build database
kraken2-build --build --db microbiome --threads 24
